DATA:
  SEED: 0
  FEATURES: [
    'MAGNETOGRAM'
  ]
  NUM_FRAMES: 1
  HEIGHT: 128
  WIDTH: 128
  TRANSFORMS: [
    'Resize',
    'Standardize'
  ]

LEARNER:
  CLASS_WEIGHT: 'balanced'
  LEARNING_RATE: 1e-2
  PATIENCE: 10
  MODEL:
    NAME: 'CNN_Li2020'
    SETTINGS: 'cnn_li2020'

TRAINER:
  max_epochs: 20
