DATA:
  SEED: 0
  FEATURES: [
    'MAGNETOGRAM'
  ]
  NUM_FRAMES: 1
  HEIGHT: 157
  WIDTH: 298
  TRANSFORMS: [
    'Resize',
    'Standardize'
  ]

LEARNER:
  CLASS_WEIGHT: 'balanced'
  #LEARNING_RATE: 1e-3
  PATIENCE: 5 # CNN has less params and more prone to overfitting
  MODEL:
    NAME: 'SimpleC3D'
    SETTINGS: 'cnn'

TRAINER:
  max_epochs: 20
